spring.application.name=DataJpaProject


spring.datasource.url= jdbc:mysql://localhost:3306/db_56
spring.datasource.username= root
spring.datasource.password= Jagadish1045@@

spring.jpa.hibernate.ddl-auto= update

spring.jpa.show-sql= true